package org.cybercraft.backend.entity;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

import java.util.List;

/**
 * Entity representing a User in the system.
 */
@Setter
@Getter
@Entity
@Table(name = "users")
public class User {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false, unique = true)
    private String username;

    /**
     * The password field is write-only to prevent it from being serialized in responses.
     */
    @JsonProperty(access = JsonProperty.Access.WRITE_ONLY)
    @Column(nullable = false)
    private String password;

    @Column(nullable = false, unique = true)
    private String email;

    /**
     * Indicates whether the user has administrative privileges.
     */
    @Column(name = "is_admin", nullable = false)
    private boolean isAdmin;

    /**
     * Token for session management or JWT (if applicable).
     * Marked as transient to prevent persistence.
     */
    @Transient
    private String token;

    /**
     * One-to-many relationship with CartItem.
     */
    @OneToMany(mappedBy = "user", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @JsonIgnore
    private List<CartItem> cart;

    /**
     * One-to-many relationship with Order.
     */
    @OneToMany(mappedBy = "user", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @JsonIgnore
    private List<Order> orders;

    // Constructors, Getters, and Setters are generated by Lombok.
}